language: java
script: mvn test
notifications:
  email:
    recipients: 
     - omardjalo@yahoo.fr 
     - edoreld@gmail.com
     - ser-katia@hotmail.fr
     - mouhhamzaoui2@hotmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "edoreld-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
